name: Continuous Integration

on: [push]

jobs:
  style:
    name: Style
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npm install && npx lerna bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_REGISTRY_READ_PACKAGES_TOKEN }}

      - name: Build
        run: npm run build

      - name: Lint commit messages
        run: npm run commitlint

      - name: Lint files with eslint
        run: npm run lint

      - name: Check formatting with prettier
        run: npm run prettier

  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
          registry-url: https://npm.pkg.github.com

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # Github Package Registry doesn't work with Yarn.
        # --update-checksums fixes this somehow
        # see https://github.com/yarnpkg/yarn/issues/7552
        # this seems to keep causing trouble, so we use
        # npm for now.
        run: npm install && npx lerna bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_REGISTRY_READ_PACKAGES_TOKEN }}

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.3.0
        with:
          coverageCommand: npm coverage --check-coverage false
        # Also publish when tests fail
        if: always()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
